version: 2.1
jobs:
  Hello-World:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

  Fetch-code:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Getting the Code
          command: |
            ls -al
            echo '^^^THE FILES IN YOUR REPO^^^'
    
  Using-Node:
    docker:
      - image: cimg/node:20.16
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v

workflows:
  Example-Workflow:
    jobs:
      - Hello-World
      - Fetch-code:
          requires:
            - Hello-World
      - Using-Node:
          requires:
            - Fetch-code

